version: '3'

services:
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"


include:
  - path: db/docker-compose.yml

volumes:
  pgdata:
