# fly.toml app configuration file generated for sac-tech-job-board-api on 2024-04-11T16:37:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sac-tech-job-board-api'
primary_region = 'sjc'

[build]
  dockerfile = './api/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 250
    soft_limit = 200

[checks]
  [checks.api_health]
    port = 8080
    type = 'http'
    interval = '15s'
    timeout = '2s'
    grace_period = '30s'
    method = 'get'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
