name: Migrate Database

on:
  push:
    branches:
      - db-migrate

jobs:
  db-migrate:
    runs-on: ubuntu-latest
    name: migrate
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup golang-migrate
        uses: docker://migrate/migrate:latest
        with:
          entrypoint: migrate
          args: "-path=/migrations -database=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@localhost:5432/${{ secrets.DB_NAME }}?sslmode=disable up"
