name: Deploy static content to Pages

on:
  push:
    branches: main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 21
      - name: Install dependencies
        run: npm ci
        working-directory: ./web
      - name: Build
        run: npm run build
        working-directory: ./web
      - name: Add CNAME record
        run: echo 'jobs.sac-tech.org' > web/dist/CNAME
      - name: Push to gh-pages subtree
        run: |
          git add -f web/dist/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m 'adding web/dist to subtree'
          git subtree push --prefix web/dist origin gh-pages
